"""atualizando dados moto

Revision ID: 14c4dc81d280
Revises: d596b57b761d
Create Date: 2022-04-27 13:54:29.765250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c4dc81d280'
down_revision = 'd596b57b761d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
