"""atualizando dados cliente

Revision ID: 156869f25f58
Revises: 52831408ab91
Create Date: 2022-04-27 12:11:19.795719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156869f25f58'
down_revision = '52831408ab91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
