"""inicial

Revision ID: 514a35611a17
Revises: 
Create Date: 2022-04-20 10:38:13.080103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514a35611a17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moto', sa.Column('modelo', sa.String(), nullable=True))
    op.add_column('moto', sa.Column('marca', sa.String(), nullable=True))
    op.add_column('moto', sa.Column('cor', sa.String(), nullable=True))
    op.add_column('moto', sa.Column('obs', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('nome', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('contato', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'contato')
    op.drop_column('usuario', 'nome')
    op.drop_column('moto', 'obs')
    op.drop_column('moto', 'cor')
    op.drop_column('moto', 'marca')
    op.drop_column('moto', 'modelo')
    # ### end Alembic commands ###
