"""atualizando dados cliente

Revision ID: 52831408ab91
Revises: cdc3b2a45433
Create Date: 2022-04-27 12:04:10.456309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52831408ab91'
down_revision = 'cdc3b2a45433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
