"""adicionando dados usuario

Revision ID: 856ab8975750
Revises: 8c0206370789
Create Date: 2022-04-26 16:17:56.251636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856ab8975750'
down_revision = '8c0206370789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
