"""adicionando novos relacionamentos

Revision ID: 8c0206370789
Revises: ae82844c5a98
Create Date: 2022-04-25 16:24:25.583788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0206370789'
down_revision = 'ae82844c5a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_cliente', type_='foreignkey')
        batch_op.create_foreign_key('fk_cliente', 'cliente', ['cliente_id'], ['id'])
        batch_op.drop_column('cliente')

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('moto_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_cliente', type_='foreignkey')
        batch_op.drop_constraint('fk_moto', type_='foreignkey')
        batch_op.create_foreign_key('fk_moto', 'moto', ['moto_id'], ['id'])
        batch_op.create_foreign_key('fk_cliente', 'cliente', ['cliente_id'], ['id'])
        batch_op.drop_column('cliente')
        batch_op.drop_column('moto')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('senha')

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moto', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('cliente', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_cliente', type_='foreignkey')
        batch_op.drop_constraint('fk_moto', type_='foreignkey')
        batch_op.create_foreign_key('fk_moto', 'moto', ['moto'], ['id'])
        batch_op.create_foreign_key('fk_cliente', 'cliente', ['cliente'], ['id'])
        batch_op.drop_column('moto_id')
        batch_op.drop_column('cliente_id')

    with op.batch_alter_table('moto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_cliente', type_='foreignkey')
        batch_op.create_foreign_key('fk_cliente', 'cliente', ['cliente'], ['id'])
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###
