"""atualizando dados moto

Revision ID: 966261809066
Revises: 14c4dc81d280
Create Date: 2022-04-27 14:37:32.736509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966261809066'
down_revision = '14c4dc81d280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.String(), nullable=True))
        batch_op.drop_column('observacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###
