"""adicionando novos relacionamentos

Revision ID: ae82844c5a98
Revises: 89f839832601
Create Date: 2022-04-25 15:01:25.939446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae82844c5a98'
down_revision = '89f839832601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
