"""atualizando dados cliente

Revision ID: cdc3b2a45433
Revises: da88d17a4aa0
Create Date: 2022-04-27 09:18:08.786300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc3b2a45433'
down_revision = 'da88d17a4aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
