"""adicionando documento cliente

Revision ID: da88d17a4aa0
Revises: 856ab8975750
Create Date: 2022-04-27 09:01:56.770915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da88d17a4aa0'
down_revision = '856ab8975750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('documento')

    # ### end Alembic commands ###
